// Exercises the greeting layout without creating or modifying guest records.
const {chromium}=require('playwright'); const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await b.newPage({reducedMotion:'reduce'});for(const width of [320,390,600,1440]){await p.setViewportSize({width,height:844});await p.goto(process.env.TEST_SITE_URL || 'http://127.0.0.1:3000/');await p.evaluate(()=>document.fonts.ready);for(const [kind,greeting]of [['couple','Dear Marthe & Deivi,'],['long','Dear Alexandra-Christine Andersen-Sørensen & Christopher Alexander Pettersen-Hansen,'],['unbroken','Dear '+ 'A'.repeat(100)+' & '+ 'B'.repeat(100)+','],['maximum','Dear '+Array.from({length:20},(_,n)=>String(n+1)+' '+ 'LongGuestName'.repeat(7)).join(' & ')+',']]){
await p.locator('#invitation-heading').evaluate((e,text)=>{e.textContent=text;e.className='personalized-greeting'},greeting);
const m=await p.evaluate(()=>{const rect=q=>document.querySelector(q).getBoundingClientRect().toJSON();const h=document.querySelector('#invitation-heading');const range=document.createRange();range.selectNodeContents(h);return{heading:rect('#invitation-heading'),copy:rect('.invitation-copy'),logo:rect('.monogram'),frame:rect('.curtain-crop'),section:rect('.home-intro'),top:rect('.curtain-top'),middle:rect('.curtain-middle'),bottom:rect('.curtain-bottom'),lines:[...range.getClientRects()].map(r=>r.toJSON()),overflow:document.documentElement.scrollWidth>innerWidth}});
assert.equal(m.overflow,false);assert.ok(m.heading.bottom<m.copy.top);assert.ok(m.copy.bottom<m.logo.top);assert.ok(m.logo.bottom<m.frame.bottom);assert.ok(m.heading.top>m.top.bottom);assert.ok(m.middle.height>0);for(const r of m.lines){assert.ok(r.left>=m.heading.left-1&&r.right<=m.heading.right+1);assert.ok(r.bottom<=m.heading.bottom+1);}console.log('PASS',width,kind,'height',m.section.height);

}}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
