"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { StoredInvitation } from "@/lib/wedding-store";
const languages = { en: "English", no: "Norwegian", lt: "Lithuanian" };
function status(invitation: StoredInvitation) {
  if (!invitation.response) return "Pending";
  const count = invitation.response.guests.filter(guest => guest.attending).length;
  return count === 0 ? "Declined" : count === invitation.guests.length ? "All attending" : "Partly attending";
}
export default function AdminDashboard({ siteUrl, view }: { siteUrl: string; view: "invitations" | "replies" }) {
  const [invitations, setInvitations] = useState<StoredInvitation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [names, setNames] = useState<string[]>([]); const [guestName, setGuestName] = useState(""); const nameInput = useRef<HTMLInputElement>(null); const [profile, setProfile] = useState("traveling"); const [language, setLanguage] = useState("en"); const [allowance, setAllowance] = useState(1);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("all"); const [replyStatus, setReplyStatus] = useState("all");
  async function load() { setError(""); try { const response = await fetch("/api/admin/invitations", { cache: "no-store" }); if (response.status === 401) { window.location.href = "/admin/login"; return; } const data = await response.json(); if (!response.ok) throw new Error(data.error); setInvitations(data.invitations); } catch (error) { setError(error instanceof Error ? error.message : "Could not load invitations."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function addName() {
    const name = guestName.trim();
    if (!name) { nameInput.current?.focus(); return; }
    if (names.length >= 20) { setError("An invitation can include up to 20 named guests."); return; }
    if (names.some(item => item.toLowerCase() === name.toLowerCase())) { setError("That name is already listed. Use full names to distinguish guests."); nameInput.current?.focus(); return; }
    setNames(current => [...current, name]); setGuestName(""); setError(""); nameInput.current?.focus();
  }
  async function create(event: FormEvent) { event.preventDefault(); const guestNames = guestName.trim() ? [...names, guestName.trim()] : names; if (!guestNames.length) { setError("Add at least one guest name."); nameInput.current?.focus(); return; } setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/invitations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ names: guestNames, travelProfile: profile, language, additionalGuestAllowance: allowance }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setInvitations(current => [data.invitation, ...current]); setNames([]); setGuestName(""); setMessage("Invitation created. Copy its link below to send by SMS."); } catch (error) { setError(error instanceof Error ? error.message : "Could not create invitation."); } finally { setBusy(false); } }
  async function toggle(invitation: StoredInvitation) { setError(""); try { const response = await fetch("/api/admin/invitations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: invitation.id, enabled: !invitation.enabled }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setInvitations(current => current.map(item => item.id === invitation.id ? { ...item, enabled: !item.enabled } : item)); } catch (error) { setError(error instanceof Error ? error.message : "Could not update invitation."); } }
  const link = (invitation: StoredInvitation) => `${siteUrl}/?invite=${invitation.token}`;
  const visible = invitations.filter(invitation => !invitation.demo && (category === "all" || invitation.travelProfile === category) && (replyStatus === "all" || status(invitation) === replyStatus) && `${invitation.label} ${invitation.guests.map(guest => guest.name).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const realInvitations = invitations.filter(invitation => !invitation.demo);
  const replies = realInvitations.filter(invitation => invitation.response);
  const attending = replies.reduce((total, invitation) => total + invitation.response!.guests.filter(guest => guest.attending).length + invitation.response!.additionalGuests.length, 0);
  function exportCsv() { const safe = (value: unknown) => { let text = String(value ?? ""); if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; }; const lines = [["Invitation", "Guests", "Category", "Language", "Status", "Attending", "Plus ones", "Hotel offer", "Venue stay", "Email", "Dietary needs", "Children under 5", "Notes", "Replied at"], ...visible.map(item => [item.label, item.guests.map(guest => guest.name).join("; "), item.travelProfile, languages[item.language], status(item), item.response?.guests.filter(guest => guest.attending).map(guest => guest.name).join("; "), item.response?.additionalGuests.map(guest => guest.name).join("; "), item.response?.hotelOffer, item.response?.venueStay, item.response?.email, item.response ? [...item.response.guests, ...item.response.additionalGuests].filter(guest => guest.dietary).map(guest => `${guest.name}: ${guest.dietary}`).join("; ") : "", item.response?.childrenNotes, item.response?.comments, item.respondedAt])]; const url = URL.createObjectURL(new Blob(["\uFEFF" + lines.map(line => line.map(safe).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "wedding-replies.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <>
    <header className="admin-heading"><div><p className="admin-eyebrow">Marthe &amp; Deivi</p><h1>{view === "replies" ? "Replies & guest categories" : "Invitations"}</h1></div><button type="button" onClick={async () => { const response = await fetch("/api/admin/session", { method: "DELETE" }); if (response.ok) window.location.href = "/admin/login"; else setError("Could not sign out. Please try again."); }}>Sign out</button></header>
    <nav className="admin-nav" aria-label="Admin navigation"><a href="/admin" aria-current={view === "invitations" ? "page" : undefined}>Invitations</a><a href="/admin/replies" aria-current={view === "replies" ? "page" : undefined}>Replies</a><a href="/" target="_blank" rel="noreferrer">Wedding website</a></nav>
    <div className="admin-stats"><div><strong>{realInvitations.length}</strong> Invitations</div><div><strong>{replies.length}</strong> Replied</div><div><strong>{realInvitations.length - replies.length}</strong> Pending</div><div><strong>{attending}</strong> Listed guests attending</div></div>
    {view === "invitations" && <section className="admin-card"><h2>Add a guest or guest group</h2><p>A couple belongs on one invitation, with both people listed by name.</p><form onSubmit={create}><label htmlFor="guest-names">Guest name</label><div className="admin-name-entry"><input id="guest-names" ref={nameInput} maxLength={100} value={guestName} onChange={event => setGuestName(event.target.value)} onKeyDown={event => { if (event.key === "Enter") { event.preventDefault(); addName(); } }} placeholder="Full name" /><button type="button" onClick={addName}>Add</button></div>{names.length > 0 && <ul className="admin-added-names">{names.map((name, index) => <li key={name}><span>{name}</span><button type="button" aria-label={`Remove ${name}`} onClick={() => setNames(current => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></li>)}</ul>}<div className="admin-form-grid"><div><label htmlFor="travel-profile">Guest category</label><select id="travel-profile" value={profile} onChange={event => setProfile(event.target.value)}><option value="traveling">Traveling guests</option><option value="local">Local guests</option></select></div><div><label htmlFor="invitation-language">Website language</label><select id="invitation-language" value={language} onChange={event => setLanguage(event.target.value)}><option value="en">English</option><option value="no">Norwegian</option><option value="lt">Lithuanian</option></select></div><div><label htmlFor="plus-one-allowance">Additional guest allowance</label><input id="plus-one-allowance" type="number" min={0} max={10} value={allowance} onChange={event => setAllowance(Number(event.target.value))} /></div></div><p className="admin-hint">Language preference is saved. Norwegian and Lithuanian translations will be added later; guests currently see English.</p><button disabled={busy}>{busy ? "Creating…" : "Create invitation link"}</button></form></section>}
    {error && <p className="rsvp-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}
    <section className="admin-card"><div className="admin-section-heading"><h2>{view === "replies" ? "Guest replies" : "Guest list & invitation links"}</h2><div><button type="button" onClick={() => void load()}>Refresh</button><button type="button" onClick={exportCsv}>Export CSV</button></div></div>
      <div className="admin-filters"><div><label htmlFor="admin-search">Search guests</label><input id="admin-search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Guest name" /></div><div><label htmlFor="category-filter">Category</label><select id="category-filter" value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option><option value="traveling">Traveling</option><option value="local">Local</option></select></div><div><label htmlFor="reply-filter">Reply status</label><select id="reply-filter" value={replyStatus} onChange={event => setReplyStatus(event.target.value)}><option value="all">All replies & pending</option>{["Pending", "All attending", "Partly attending", "Declined"].map(value => <option key={value}>{value}</option>)}</select></div></div>

      {loading ? <p>Loading invitations…</p> : !visible.length ? <p>No invitations match yet.</p> : <div className="admin-table-wrap"><table><thead><tr><th>Guests</th><th>Category / language</th><th>Reply</th><th>Group option</th><th>Email address</th><th>Invitation link</th></tr></thead><tbody>{visible.map(invitation => <tr key={invitation.id}>
        <td data-label="Guests">{invitation.guests.map(guest => <span key={guest.id}><strong>{guest.name}</strong></span>)}{!invitation.enabled && <span className="admin-badge">Link revoked</span>}</td>
        <td data-label="Category / language">{invitation.travelProfile === "traveling" ? "Traveling" : "Local"}<span>{languages[invitation.language]}</span></td>
        <td data-label="Reply">{invitation.response && <><ul className="admin-guest-replies">{invitation.response.guests.map(guest => <li key={guest.guestId}><strong>{guest.name}:</strong> {guest.attending ? "Yes" : "No"}</li>)}{invitation.response.additionalGuests.map(guest => <li key={guest.id}><strong>{guest.name} (plus one):</strong> Yes</li>)}</ul><details><summary>More details</summary>{[...invitation.response.guests, ...invitation.response.additionalGuests].filter(guest => guest.dietary).map((guest, index) => <p key={index} className="admin-notes">{guest.name} — Dietary: {guest.dietary}</p>)}{invitation.response.childrenNotes && <p className="admin-notes">Children under 5: {invitation.response.childrenNotes}</p>}{invitation.response.comments && <p className="admin-notes">Notes: {invitation.response.comments}</p>}{invitation.respondedAt && <p>Replied: {new Date(invitation.respondedAt).toLocaleString("en-GB", { timeZone: "Europe/Oslo" })}</p>}</details></>}</td>
        <td data-label="Group option">{invitation.response && (invitation.travelProfile === "traveling" ? invitation.response.hotelOffer : invitation.response.venueStay) && <><strong>{(invitation.travelProfile === "traveling" ? invitation.response.hotelOffer : invitation.response.venueStay) === "yes" ? "Yes" : "No"}</strong><span>{invitation.travelProfile === "traveling" ? "Kaunas hotel · Sep 3–4" : "Venue stay · Sep 4–5"}</span></>}</td>
        <td data-label="Email address">{invitation.response?.email && <a className="admin-email" href={`mailto:${invitation.response.email}`}>{invitation.response.email}</a>}</td>
        <td data-label="Invitation link"><a className="admin-invite-url" href={link(invitation)} target="_blank" rel="noreferrer">{link(invitation)}</a><div className="admin-row-actions"><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(link(invitation)); setMessage(`Link copied for ${invitation.guests.map(guest => guest.name).join(" & ")}.`); } catch { setError("Copy the visible invitation link manually."); } }}>Copy link</button><button type="button" onClick={() => void toggle(invitation)}>{invitation.enabled ? "Revoke link" : "Restore link"}</button></div></td>
      </tr>)}</tbody></table></div>}
    </section>
    {siteUrl.includes("localhost") || siteUrl.includes("127.0.0.1") ? <p className="admin-hint">These links work on this computer. Set SITE_URL to your public HTTPS address when hosting the site, so guests and SMS previews can access them.</p> : null}
  </>;
}
